import os
import json
import logging
from typing import Dict, Any, Generator, Tuple
from google.adk import Agent, Workflow
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from core.schemas import (
    ProfileAnalysisOutput,
    BusinessIdeasOutput,
    MarketAnalysisOutput,
    FinancialPlanOutput,
    GovernmentSupportOutput,
    LaunchRoadmapOutput,
    RiskAssessmentOutput
)
from core.tools import (
    fetch_market_demands,
    calculate_financials,
    search_government_schemes,
    evaluate_industry_risks
)

# Setup logging
logger = logging.getLogger("Dream2BusinessWorkflow")

# Model configuration
DEFAULT_MODEL = "gemini-2.5-flash"

# Define the 7 ADK Agents with their respective instructions, tools, and output schemas
profile_agent = Agent(
    name="ProfileAnalysisAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Profile Analysis Agent. Your role is to analyze the user's input profile: "
        "their skills, budget, education, location, and interests. "
        "Evaluate their strengths, identify potential skill or educational gaps, analyze local constraints based on their location, "
        "and determine whether their budget is feasible for starting a business. "
        "Provide recommended focus areas. "
        "You MUST respond ONLY in valid JSON matching the ProfileAnalysisOutput schema."
    ),
    output_schema=ProfileAnalysisOutput
)

idea_agent = Agent(
    name="BusinessIdeaAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Business Idea Agent. Based on the user profile inputs and the ProfileAnalysisAgent's summary, "
        "generate 3 creative, high-potential business ideas. "
        "For each idea, provide a clear concept description, identify its target industry, assign an alignment score (1-100), "
        "specify the target customer segment, and write a detailed rationale for why it fits the user. "
        "Identify the single top idea that is best suited to start. "
        "You MUST respond ONLY in valid JSON matching the BusinessIdeasOutput schema."
    ),
    output_schema=BusinessIdeasOutput
)

market_agent = Agent(
    name="MarketResearchAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Market Research Agent. Your task is to perform market research on the top-selected business idea "
        "generated by the BusinessIdeaAgent. "
        "You MUST use the fetch_market_demands tool to get local market demand indices, competitor densities, and trends. "
        "Compile the target audience, market size estimation, competitor analysis, and key trends, "
        "then provide a demand validation verdict. "
        "You MUST respond ONLY in valid JSON matching the MarketAnalysisOutput schema."
    ),
    tools=[fetch_market_demands],
    output_schema=MarketAnalysisOutput
)

financial_agent = Agent(
    name="FinancialPlanningAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Financial Planning Agent. Your task is to create a realistic financial plan for the top business idea "
        "validated by the MarketResearchAgent. "
        "You MUST use the calculate_financials tool to run cash flow projections and break-even calculations. "
        "Design the itemized startup costs (licenses, marketing, equipment, inventory, operational reserve) such that "
        "the total fits within the user's budget. Suggest pricing strategies, fixed monthly expenses, and "
        "variable cost per unit. Provide a 12-month revenue forecast and calculate break-even months. "
        "You MUST respond ONLY in valid JSON matching the FinancialPlanOutput schema."
    ),
    tools=[calculate_financials],
    output_schema=FinancialPlanOutput
)

government_agent = Agent(
    name="GovernmentSchemeAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Government Scheme Agent. Your task is to identify government programs, grants, subsidies, and microloans "
        "available in the user's location for their specific business industry. "
        "You MUST use the search_government_schemes tool to fetch applicable programs. "
        "Detail the benefits, eligibility, application steps, and local registration requirements. "
        "You MUST respond ONLY in valid JSON matching the GovernmentSupportOutput schema."
    ),
    tools=[search_government_schemes],
    output_schema=GovernmentSupportOutput
)

launch_agent = Agent(
    name="LaunchStrategyAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Launch Strategy Agent. Your task is to create a detailed, action-oriented 30-day business launch roadmap "
        "based on the business plan, financials, and local requirements. "
        "Organize the timeline week-by-week: Week 1 (Setup & Legal), Week 2 (Branding & MVP Product), "
        "Week 3 (Marketing & Initial Sales), Week 4 (Launch & Feedback). "
        "Provide daily actionable checklist tasks and key milestones. "
        "You MUST respond ONLY in valid JSON matching the LaunchRoadmapOutput schema."
    ),
    output_schema=LaunchRoadmapOutput
)

risk_agent = Agent(
    name="RiskAssessmentAgent",
    model=DEFAULT_MODEL,
    instruction=(
        "You are the Risk Assessment Agent. Your task is to analyze potential risks for starting and running this business. "
        "You MUST use the evaluate_industry_risks tool to analyze industry-specific risks. "
        "Categorize risks into Financial, Market, Operational, and Legal/Regulatory. "
        "For each risk, assign probability, severity, and write a detailed mitigation strategy. "
        "Provide recommended business insurances and a regulatory compliance checklist. "
        "You MUST respond ONLY in valid JSON matching the RiskAssessmentOutput schema."
    ),
    tools=[evaluate_industry_risks],
    output_schema=RiskAssessmentOutput
)

# Chained ADK Workflow defining the complete multi-agent graph architecture
adk_workflow = Workflow(
    name="Dream2BusinessWorkflow",
    edges=[
        ("START", profile_agent),
        (profile_agent, idea_agent),
        (idea_agent, market_agent),
        (market_agent, financial_agent),
        (financial_agent, government_agent),
        (government_agent, launch_agent),
        (launch_agent, risk_agent)
    ]
)

class ADKOrchestrator:
    """
    Manages the sequential execution of Google ADK agents and stores/returns intermediate structured outputs.
    Ensures that context passes correctly between agents and validates/recovers JSON outputs.
    """
    def __init__(self):
        self.session_service = InMemorySessionService()

    def run_agent(self, agent: Agent, user_id: str, session_id: str, prompt: str) -> str:
        """
        Executes a single agent with the given prompt using the ADK Runner.
        Returns the raw string output of the agent.
        """
        runner = Runner(agent=agent, app_name="Dream2Business", session_service=self.session_service)
        
        # Create user input message
        new_message = types.Content(parts=[types.Part.from_text(text=prompt)])
        
        result = runner.run(
            user_id=user_id,
            session_id=session_id,
            new_message=new_message
        )
        
        raw_output = ""
        for event in result:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        raw_output += part.text
                        
        return raw_output

    def parse_and_validate_json(self, raw_text: str, schema_class: Any) -> Dict[str, Any]:
        """
        Cleans markdown wrappers (like ```json ... ```) from the agent's output,
        parses the JSON, and validates it against the expected Pydantic schema class.
        """
        # Strip markdown markers
        cleaned = raw_text.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()

        # Find outer boundaries of JSON object if there's surrounding text
        start_idx = cleaned.find("{")
        end_idx = cleaned.rfind("}")
        if start_idx != -1 and end_idx != -1:
            cleaned = cleaned[start_idx:end_idx + 1]

        # Parse JSON
        parsed_data = json.loads(cleaned)
        
        # Validate using Pydantic model
        validated_model = schema_class.model_validate(parsed_data)
        
        # Return as python dictionary
        return validated_model.model_dump()

    def execute_full_analysis(self, profile: Dict[str, Any], user_id: str, session_id: str) -> Generator[Tuple[str, str, Dict[str, Any]], None, None]:
        """
        Runs the full 7-agent pipeline sequentially, yielding progress and results.
        Yields: (agent_name, status, data)
        """
        # 1. Profile Analysis
        yield ("ProfileAnalysisAgent", "running", {})
        try:
            profile_prompt = (
                f"Analyze this user profile:\n"
                f"- Skills: {profile['skills']}\n"
                f"- Budget: ${profile['budget']}\n"
                f"- Education: {profile['education']}\n"
                f"- Location: {profile['location']}\n"
                f"- Interests: {profile['interests']}\n\n"
                f"Provide a rigorous feasibility and readiness assessment."
            )
            raw = self.run_agent(profile_agent, user_id, session_id, profile_prompt)
            profile_data = self.parse_and_validate_json(raw, ProfileAnalysisOutput)
            yield ("ProfileAnalysisAgent", "completed", profile_data)
        except Exception as e:
            logger.error(f"Error in ProfileAnalysisAgent: {e}")
            yield ("ProfileAnalysisAgent", "failed", {"error": str(e)})
            return

        # 2. Business Ideas Generation
        yield ("BusinessIdeaAgent", "running", {})
        try:
            ideas_prompt = (
                f"User Profile Inputs:\n"
                f"- Skills: {profile['skills']}\n"
                f"- Budget: ${profile['budget']}\n"
                f"- Location: {profile['location']}\n"
                f"- Interests: {profile['interests']}\n\n"
                f"Profile Analysis Summary:\n"
                f"{json.dumps(profile_data, indent=2)}\n\n"
                f"Generate 3 highly tailored business ideas."
            )
            raw = self.run_agent(idea_agent, user_id, session_id, ideas_prompt)
            ideas_data = self.parse_and_validate_json(raw, BusinessIdeasOutput)
            yield ("BusinessIdeaAgent", "completed", ideas_data)
        except Exception as e:
            logger.error(f"Error in BusinessIdeaAgent: {e}")
            yield ("BusinessIdeaAgent", "failed", {"error": str(e)})
            return

        # Select top business idea
        try:
            top_idea = ideas_data["ideas"][0]
            top_idea_name = top_idea["idea_name"]
            top_idea_industry = top_idea["target_industry"]
        except (KeyError, IndexError):
            top_idea_name = "Custom Services Startup"
            top_idea_industry = "General Business Services"

        # 3. Market Research
        yield ("MarketResearchAgent", "running", {})
        try:
            market_prompt = (
                f"Conduct market demand validation and analysis for:\n"
                f"- Selected Idea: {top_idea_name}\n"
                f"- Location: {profile['location']}\n"
                f"- Industry: {top_idea_industry}\n\n"
                f"Profile Context:\n"
                f"{json.dumps(profile_data, indent=2)}\n\n"
                f"Use the fetch_market_demands tool to query the local market."
            )
            raw = self.run_agent(market_agent, user_id, session_id, market_prompt)
            market_data = self.parse_and_validate_json(raw, MarketAnalysisOutput)
            yield ("MarketResearchAgent", "completed", market_data)
        except Exception as e:
            logger.error(f"Error in MarketResearchAgent: {e}")
            yield ("MarketResearchAgent", "failed", {"error": str(e)})
            return

        # 4. Financial Plan
        yield ("FinancialPlanningAgent", "running", {})
        try:
            finance_prompt = (
                f"Build a startup financial model and projections for:\n"
                f"- Business Idea: {top_idea_name}\n"
                f"- Target Location: {profile['location']}\n"
                f"- User Startup Capital Limit: ${profile['budget']}\n\n"
                f"Market Research Analysis Context:\n"
                f"{json.dumps(market_data, indent=2)}\n\n"
                f"Use the calculate_financials tool to establish itemized costs, pricing, and revenue projections."
            )
            raw = self.run_agent(financial_agent, user_id, session_id, finance_prompt)
            financial_data = self.parse_and_validate_json(raw, FinancialPlanOutput)
            yield ("FinancialPlanningAgent", "completed", financial_data)
        except Exception as e:
            logger.error(f"Error in FinancialPlanningAgent: {e}")
            yield ("FinancialPlanningAgent", "failed", {"error": str(e)})
            return

        # 5. Government Support
        yield ("GovernmentSchemeAgent", "running", {})
        try:
            gov_prompt = (
                f"Search for grants, programs, and subsidies for this business:\n"
                f"- Business Concept: {top_idea_name}\n"
                f"- Industry: {top_idea_industry}\n"
                f"- Location: {profile['location']}\n\n"
                f"Financial Projections Context:\n"
                f"{json.dumps(financial_data, indent=2)}\n\n"
                f"Use the search_government_schemes tool to retrieve eligibility and steps."
            )
            raw = self.run_agent(government_agent, user_id, session_id, gov_prompt)
            government_data = self.parse_and_validate_json(raw, GovernmentSupportOutput)
            yield ("GovernmentSchemeAgent", "completed", government_data)
        except Exception as e:
            logger.error(f"Error in GovernmentSchemeAgent: {e}")
            yield ("GovernmentSchemeAgent", "failed", {"error": str(e)})
            return

        # 6. Launch Roadmap
        yield ("LaunchStrategyAgent", "running", {})
        try:
            launch_prompt = (
                f"Design a 30-day tactical week-by-week launch roadmap for:\n"
                f"- Business Concept: {top_idea_name}\n"
                f"- Location: {profile['location']}\n\n"
                f"Financial Model Summary:\n"
                f"{json.dumps(financial_data, indent=2)}\n\n"
                f"Government and Registration Context:\n"
                f"{json.dumps(government_data, indent=2)}"
            )
            raw = self.run_agent(launch_agent, user_id, session_id, launch_prompt)
            launch_data = self.parse_and_validate_json(raw, LaunchRoadmapOutput)
            yield ("LaunchStrategyAgent", "completed", launch_data)
        except Exception as e:
            logger.error(f"Error in LaunchStrategyAgent: {e}")
            yield ("LaunchStrategyAgent", "failed", {"error": str(e)})
            return

        # 7. Risk Assessment
        yield ("RiskAssessmentAgent", "running", {})
        try:
            risk_prompt = (
                f"Conduct a risk analysis and mitigation plan for:\n"
                f"- Business: {top_idea_name}\n"
                f"- Industry: {top_idea_industry}\n"
                f"- Location: {profile['location']}\n\n"
                f"Financial Plan Context:\n"
                f"{json.dumps(financial_data, indent=2)}\n\n"
                f"Roadmap Plan Context:\n"
                f"{json.dumps(launch_data, indent=2)}\n\n"
                f"Use the evaluate_industry_risks tool to analyze threats."
            )
            raw = self.run_agent(risk_agent, user_id, session_id, risk_prompt)
            risk_data = self.parse_and_validate_json(raw, RiskAssessmentOutput)
            yield ("RiskAssessmentAgent", "completed", risk_data)
        except Exception as e:
            logger.error(f"Error in RiskAssessmentAgent: {e}")
            yield ("RiskAssessmentAgent", "failed", {"error": str(e)})
            return
